#!/usr/bin/env Rscript

args <- commandArgs(trailingOnly = TRUE)
if (length(args) != 1) {
  stop("Usage: Rscript generate_web.R <output_file>")
}

output_file <- args[1]
dir.create(dirname(output_file), recursive = TRUE, showWarnings = FALSE)

today <- as.character(Sys.Date())
r_version <- paste(R.version$major, R.version$minor, sep = ".")

html <- c(
  "<!doctype html>",
  "<html lang=\"en\">",
  "<head>",
  "  <meta charset=\"utf-8\" />",
  "  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\" />",
  "  <title>marcnava.42.fr/web</title>",
  "  <style>",
  "    body {",
  "      margin: 0;",
  "      font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;",
  "      background: #f4f9ff;",
  "      min-height: 100vh;",
  "      display: grid;",
  "      place-items: center;",
  "      color: #102a43;",
  "    }",
  "    .card {",
  "      width: min(700px, 92vw);",
  "      background: #ffffff;",
  "      border: 1px solid #d9e2ec;",
  "      border-radius: 14px;",
  "      padding: 2rem;",
  "      box-shadow: 0 14px 32px rgba(16, 42, 67, 0.08);",
  "    }",
  "    h1 { margin-top: 0; }",
  "    code {",
  "      background: #f0f4f8;",
  "      border: 1px solid #d9e2ec;",
  "      border-radius: 6px;",
  "      padding: 0.15rem 0.35rem;",
  "    }",
  "  </style>",
  "</head>",
  "<body>",
  "  <main class=\"card\">",
  "    <h1>Static Bonus Website</h1>",
  "    <p>This page is generated by an <code>R</code> script at image build time.</p>",
  paste0("    <p>Build date: <code>", today, "</code></p>"),
  paste0("    <p>R version used: <code>", r_version, "</code></p>"),
  "    <p>Served through: <code>https://marcnava.42.fr/web</code></p>",
  "  </main>",
  "</body>",
  "</html>"
)

writeLines(html, output_file, useBytes = TRUE)
