listen=YES
listen_ipv6=NO

anonymous_enable=NO
local_enable=YES
write_enable=YES
local_umask=002

dirmessage_enable=YES
xferlog_enable=YES
connect_from_port_20=YES
use_localtime=YES

chroot_local_user=YES
allow_writeable_chroot=YES
local_root=/var/www/html

pasv_enable=YES
pasv_min_port=__FTP_PASV_MIN_PORT__
pasv_max_port=__FTP_PASV_MAX_PORT__

pam_service_name=vsftpd
seccomp_sandbox=NO
ftpd_banner=Inception FTP server ready.
